repos:
  - repo: local
    hooks:
      - id: ruff-lint-fix
        name: "Ruff – Lint"
        entry: uv run ruff check --fix
        language: system
        types: [python]

      - id: ruff-format
        name: "Ruff - Format"
        entry: "uv run ruff format"
        language: system
        types: [python]

  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.4.1
    hooks:
      - id: commitizen
        name: "Commitizen – Enforce Conventional Commit Message"
        stages: [commit-msg]
